title: Bennett Hardwick
email: me (at) bennetthardwick (dot) com
description: "The result of torturous tinkering and misplaced motivation. I'm just waiting for things to break."
baseurl: "/"
url: "https://bennetthardwick.com"

github_username:  bennetthardwick

google-verify: u78IFZOKDz1NPqmKsANfQmHlVEpW4hiNldikm8m94ls

markdown: kramdown

collections:
  projects:
    output: true

author: Bennett Hardwick

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

paginate: 8
paginate_path: "/blog/page/:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-feed
  - jemoji
