baseURL = "https://bennetthardwick.com/"
languageCode = "en"
title = "Bennett's Rust Journal"
summaryLength = 40
canonifyURLs = true

[outputs]
page = [ "HTML", "AMP" ]

[params]

description = "The personal website and thoughts of me Bennett Hardwick - Software Developer living in Brisbane and working at Clipchamp."

twitter = "bennettbackward"

gtag = "UA-153493405-1"

json_ld_time_format = "2006-01-02T15:04:05JST"

profile = "icon.png"
profile_large = "profile.jpg"

footer_about = """
Bennett is a Software Engineer working at [Clipchamp](https://clipchamp.com).
He spends most of his day playing with React and Gatsby, and editing videos and his nights programming in Rust.
You can follow him on [Github](https://github.com/bennetthardwick) or [Twitter](https://twitter.com/bennettbackward).
"""

accent = "#2f76d0"
accent_light = "#82ade3"

[markup.highlight]
noClasses = false
guessSyntax = true

[permalinks]
projects = "/:section/:slug/"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1


[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[taxonomies]
  tags = "tags"
