[build]
# This assumes that the Zola site is in a docs folder. If it isn't, you don't need
# to have a `base` variable but you do need the `publish` and `command` variables.
base    = "."
publish = "./output"
command = """
zola build && \
wget https://github.com/bennetthardwick/static-site-to-amp/releases/download/0.2.0/static-site-to-amp && \
chmod +x ./static-site-to-amp && \
./static-site-to-amp ./public --base-url https://bennetthardwick.com --outdir ./output
"""

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.9.0"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = """
zola build --base-url $DEPLOY_PRIME_URL && \
wget https://github.com/bennetthardwick/static-site-to-amp/releases/download/0.2.0/static-site-to-amp && \
chmod +x ./static-site-to-amp && \
./static-site-to-amp ./public --base-url $DEPLOY_PRIME_URL --outdir ./output
"""
