[build]
base    = "."
publish = "./public"
command = "npm run index-wiki && hugo --gc --minify && ./replace-amp-images ./public/amp"

[build.environment]
HUGO_VERSION = "0.74.3"

[context.deploy-preview]
command = "npm run index-wiki && hugo --gc --minify -b $DEPLOY_PRIME_URL && ./replace-amp-images ./public/amp"
